data-folder: example_data
chessboard-size: 12.0 # mm
chessboard-height: 7
chessboard-width: 10
visualize-2D: true # project 2D target frames to images and save
visualize-3D: true # plot 3D frames in viser
method: tsai # my_method, tsai or park