data-folder: example_data
chessboard-size: 28.5 # mm
chessboard-height: 8
chessboard-width: 6
visualize-2D: false # project 2D target frames to images and save
visualize-3D: false # plot 3D frames in viser