handeye:
  data-folder: /home/nikolai/repos/LF_data_collection/calib_cam2arm
  chessboard-size: 20.0 # mm
  chessboard-height: 7
  chessboard-width: 12
  visualize-2D: false # project 2D target frames to images and save
  visualize-3D: false # plot 3D frames in viser
  method: my_method # my_method, tsai or park

target-cal:
  data-folder: /home/nikolai/repos/LF_data_collection/calib_cam2arm
  handeye-result: /home/nikolai/repos/LF_data_collection/calib_cam2arm/result.h5
  chessboard-size: 20.0 # mm
  chessboard-height: 7
  chessboard-width: 12
  visualize-2D: true # project 2D target frames to images and save
  visualize-3D: true # plot 3D frames in viser